


      SUBROUTINE READFILEX(FILEX)


      USE ModuleDefs

      IMPLICIT NONE

      CHARACTER* 12 FILEX

      print *, FILEX

C       CALL IPEXP (MODEL, RUN, RNMODE, FILEX,PATHEX,FILEX_P, FILECTL,
C     &     SLNO,NYRS,VARNO,CROP,WMODI,
C     &     FROP,TRTN,EXPP,EXPN,TITLET,TRTALL,TRTNUM,ROTNUM, 
C     &     IIRV,FTYPEN,CHEXTR,NFORC,PLTFOR,NDOF,PMTYPE,
C     &     LNSIM,LNCU,LNHAR,LNENV,LNTIL,LNCHE,
C     &     LNFLD,LNSA,LNIC,LNPLT,LNIR,LNFER,LNRES, 
C     &     CONTROL, ISWITCH, UseSimCtr, MODELARG)



      END SUBROUTINE


